site_name: SerialBox Dox
pages:
  - Home: 
      - Welcome: index.md
      - Installation: installation.md
      - Basic Concepts: basic_concepts.md
      - Environment Variables: environment_variables.md
      - Settings: settings.md
      - The Pool API: pool-api.md
      - The Sequential Region API: region-api.md
      - The Number Allocation API: allocate.md
      - Extending SerialBox: extending.md
      - Pre and Post Processing Rules: rules.md
      - Custom FlavorPacks: flavorpacks.md
      - Custom Rules: custom-rules.md
      - Release Notes: history.md
  
theme: readthedocs
use_directory_urls: false
repo_url: https://gitlab.com/serial-lab/serialbox