# Generated by Django 2.0.1 on 2018-10-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialbox', '0004_auto_20181015_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responserule',
            unique_together={('content_type', 'pool')},
        ),
    ]
