# Generated by Django 2.1.5 on 2019-01-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialbox', '0005_auto_20181031_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['readable_name', 'machine_name'], 'permissions': (('allocate_numbers', 'Can allocate numbers.'),), 'verbose_name': 'Pool', 'verbose_name_plural': 'Pools'},
        ),
    ]
