# Generated by Django 3.1.4 on 2021-08-18 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serialbox', '0009_auto_20210818_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(blank=True, db_index=True, help_text='The response data', null=True, verbose_name='Response'),
        )
    ]
