# Generated by Django 3.1.4 on 2021-08-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialbox', '0010_auto_20210818_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(blank=True, help_text='The response data', null=True, verbose_name='Response'),
        ),
    ]
